# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
   VERISON: 0

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/AzureStorage/Queue/Queue
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Queue.csproj
    - name: Dotnet Build
      run: dotnet build Queue.csproj -c Release --no-restore
    - name: Dotnet Pack
      run: dotnet pack -c Release Queue.csproj
    - name: Get CSProj Version      
      id: package_version
      uses: KageKirin/get-csproj-version@v1.0.0
      with:        
        file: src/AzureStorage/Queue/Queue/Queue.csproj      
    - name: Publish to Nuget
      run: dotnet nuget push --source https://api.nuget.org --api-key ${{secrets.NUGET_API_KEY}} 'src/AzureStorage/Queue/Queue/bin/Release/Devmonster.AzureStorage.Queue.${{ steps.package_version.version }}.nupkg'
      
